### PR TITLE
Javtheslav patch 1

### PR DESCRIPTION
**Pull request by javtheslav**

### CODE REVIEW

**Review by tizu69 — CHANGES_REQUESTED** [review]
- Mailto is intentionally left out, bot crawlers often ignore robots.txt and may spam emails
- The hell is the 10th? I would personally leave users out that aren't on the team yet

**Comment by Projectmaster122** [comment]
i did, i removed it tho

**Comment by Projectmaster122** [comment]
he just needs to pull and ittl come back

**Comment by Projectmaster122** [comment]
to normal

**Comment by usarana** [comment]
Tizu is right

**Pull request closed without merging**
