### PR TITLE
feat/gh-pr

### PR DESCRIPTION
**Pull request by tizu69**
# feat/gh-pr

**Doesn't fix any issue**

## The following still has to be done

[x] Run `pnpm format`
[x] Target the dev branch (never main!)
[x] Create a branch named the same as the title on my fork
[x] Lint using `pnpm lint` and fix all warnings and errors
[x] Check using `pnpm check`

## I did the following

Added a PR checklist and gone through the checklist and executed needed actions

### CODE REVIEW

**Comment by tizu69** [comment]
only reason why I want to enforce the naming scheme is this
image

**Review by Projectmaster122 — CHANGES_REQUESTED** [review]
remove checklist wen.

**Comment by usarana** [comment]
everything.

**Comment by tizu69** [comment]
> everything.

well then u'll get the most inconsistent code you could ever imagine

**Comment by usarana** [comment]
good

**Comment by tizu69** [comment]
that's stupid tho

**Comment by usarana** [comment]
we wish you all the best (jk)

**Pull request closed without merging**
